export const DS = {
  navy:          '#011e4b',
  navyLight:     '#1c3461',
  gold:          '#785a00',
  goldLight:     '#fed16c',
  goldDim:       '#ecc15d',
  parchment:     '#fff8f2',
  parchmentLow:  '#fff2df',
  parchmentMid:  '#ffebcb',
  parchmentDim:  '#ebd8b8',
  cream:         '#f4ece1',
  inkDark:       '#241a07',
  inkLight:      '#44474f',
  outline:       '#757780',
  outlineVar:    '#c4c6d0',
  bronze:        '#b89871',
  white:         '#ffffff',
  error:         '#ba1a1a',
  fontDisplay:   "'Cormorant Garamond', 'Playfair Display', serif",
  fontBody:      "'Inter', sans-serif",
  fontMono:      "'JetBrains Mono', monospace",
};
